Feature/pep612 support
uwcirg/fhir-migrations pull request #3
Opened 2024-06-15 20:43 UTC by Filienko

2024-06-19 02:13 UTC, pbugni requested changes

2024-06-19 02:13 UTC, pbugni commented on README.md
> +- For writing new migrations: the random UUID for the migration's revision id is generated automatically and does not need to be specified by user. The upgrade method is run on `upgrade` flask comman
unless i'm overlooking it, you don't mention `how` to generate the migration script here?

2024-06-19 02:13 UTC, pbugni commented on README.md
> +To initialize the Migration service and use a specific directory for migration scripts, you need to provide the path to the directory when creating an instance of the Migration class. By default, the
s/in examples/in the nested examples/

2024-06-19 02:13 UTC, pbugni commented on README.md
> +- For writing new migrations: the random UUID for the migration's revision id is generated automatically and does not need to be specified by user. The upgrade method is run on `upgrade` flask comman
something like "see the `migration` command, below

2024-06-19 02:13 UTC, pbugni commented on README.md
> +Provided is a simple set of migration scripts that create a patient and then modify it. The operation was limited to one patient to limit potential interference with existing stores. However, the com
s/set of/set of example/

2024-06-19 02:13 UTC, pbugni commented on pyproject.toml
> +description = "The module captures essential methods for system migration, including running downgrade functions for stepping back during downgrades and applying upgrades, which execute upgrade funct
I'd expand your description to include details about being designed to work with a FHIR store.  How it tracks the latest upgrade run against your store in a Basic FHIR resource, etc.

2024-06-20 18:40 UTC, ivan-c requested changes
looks good! the version may be a blocker, but all other comments are nitpicks.

@Filienko please add a description to the PR when you get a chance

thank you!

2024-06-20 18:40 UTC, ivan-c commented on README.md
> +   `ENV MIGRATION_SCRIPTS_DIR=$SCRIPT_DIR`
I **think** you intended these to be separate lines, which needs slightly different markdown

```suggestion
On Unix-based systems, you can set the `MIGRATION_SCRIPTS_DIR` environment variable like this:

    export MIGRATION_SCRIPTS_DIR="/path/to/custom/migration_scripts_directory"

Or in the corresponding Dockerfile of your service by specifying MIGRATION_SCRIPTS_DIR 

    ENV MIGRATION_SCRIPTS_DIR=$SCRIPT_DIR
```

2024-06-20 18:40 UTC, ivan-c commented on fhir_migrations/examples/add_mrn.py
> +    if response.status_code == 200:
you might try a [guard clause](https://en.wikipedia.org/wiki/Guard_(computer_science)) here so the code is flatter. ie inverting the condition to fail on non-200 earlier

2024-06-20 18:40 UTC, ivan-c commented on pyproject.toml
> +version = "0.0.1"
we typically try to manage the versioning via git/VCS. using a static version here may conflict with the VCS reports
```suggestion
dynamic = ["version"]
```

2024-06-20 18:40 UTC, ivan-c commented on pyproject.toml
> +    { name="CIRG", email="cirg@example.com" }
```suggestion
    { name="CIRG", email="cirg-adm@uw.edu" }
```

2024-06-20 20:43 UTC, ivan-c approved these changes
looks great, thanks again!!

2024-06-20 20:49 UTC, merged